title: Building Blocks Towards Linux | ROADMAP
author:
  name: Yahya Abulhaj
  email: dev@yahya-abulhaj.dev
description: >
  When it comes to learning Linux, there are a variety of different approaches that one can take to gain a deeper understanding of the operating system. That is my user-friendly attempt at how I believe you should begin learning Linux.

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
social_links:
  - platform: hashnode
    user_url: "https://blog.yahya-abulhaj.dev/"
  - platform: github
    user_url: "https://github.com/Y4HYA4"
  - platform: instagram
    user_url: "https://www.instagram.com/yaya2devops/"
  - platform: linkedin
    user_url: "https://www.linkedin.com/in/yahya-abulhaj/"
header_pages:
  - about.md
show_excerpts: true
